version: '3.5'

services:
  perpus-ahmad1510520140:
    container_name: perpus-ahmad1510520140
    image: img-perpus-ahmad1510520140
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    networks:
      backend:
        aliases:
          - app

  mysql-db:
    container_name: mysql-db
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: passworddiskominfo!
      MYSQL_USER: user
      MYSQL_PASSWORD: passworddiskominfo@
    volumes:
      - mysql:/var/lib/mysql
    networks:
      backend:
        aliases:
          - mysql-db

    deploy:
      resources:
        limits:
          memory: 768M
          cpus: "0.50"
    restart: always
#  mysql-db:
 #   image: mysql:5.7
  #  container_name: mysql-db
   # volumes:
    #  - ./run/var:/var/lib/mysql
    #environment:
     #- MYSQL_ROOT_PASSWORD=password
     # - MYSQL_USER=user
     # - MYSQL_PASSWORD=password
    #networks:
     # backend:
      #  aliases:
       #   - mysql-db

networks:
  backend:
    name: backend-network
volumes:
  mysql:
    external: false
